version: '3'
services: 
    dev:
        image: devcontainer:java-selenium
        container_name: java-selenium
        volumes: 
            - ../:/workspace
            - .m2:/root/.m2
        tty: true
