version: '3'
services: 
    dev:
        image: devcontainer:java-selenium
        container_name: java-selenium
        volumes: 
            - ../:/workspace
            - .m2:/root/.m2
            - ./extensions/:/root/.vscode-server/extensions/
        tty: true
        depends_on:
            - web
            - chromedriver
    web:
        image: devcontainer:node
        container_name: sample-web
        volumes: 
            - ../src/test/resources/sampleweb:/app
        entrypoint: serve /app -l 3000
        ports: 
            - "3000:3000"
    chromedriver:
        image: selenium/standalone-chrome-debug
        container_name: chromedriver
        # volumes:
        #     - /dev/shm:/dev/shm
        ports: 
            - "4444:4444"
